import type { CatalogProduct } from "@/components/CatalogPageLayout";

export const catalog: CatalogProduct[] = [
  {
    id: "m-1",
    name: "Mens Short Sleeves Polo Shirt - Slim Fit",
    category: "Mens Polo",
    brand: "Loomora",
    price: 1290,
    color: "#6b7280",
    colorName: "Grey Melange",
    src: "/images/men/men.avif",
    badge: "New",
    sizes: ["36", "38", "40", "42", "44"],
    fabric: "Cotton & Spandex",
    fit: "Slim Fit",
    sleeve: "Half Sleeve",
    neck: "Rib Collar",
    length: "Short",
    productType: "Polo",
    addition: ["Embroidery"],
    festive: ["Boishak 2026"],
  },
  {
    id: "m-2",
    name: "Mens Short Sleeves Polo Shirt - Slim Fit",
    category: "Mens Polo",
    brand: "Loomora",
    price: 1290,
    color: "#0f766e",
    colorName: "Sea Green",
    src: "/images/men/w-1.jpg",
    badge: "New",
    sizes: ["36", "38", "40", "42"],
    fabric: "Cotton & Lycra",
    fit: "Slim Fit",
    sleeve: "Half Sleeve",
    neck: "Rib Collar",
    length: "Short",
    productType: "Polo",
  },
  {
    id: "m-3",
    name: "Mens Dark Wash Denim Pant - Slim Fit",
    category: "Mens Jeans Pant",
    brand: "DHEU",
    price: 1990,
    color: "#1e3a8a",
    colorName: "Dark Blue",
    src: "/images/men/w-2.jpg",
    badge: "New",
    sizes: ["30", "32", "34", "36"],
    fabric: "Denim",
    fit: "Slim Fit",
    length: "Full Length",
    productType: "Denim",
  },
  {
    id: "m-4",
    name: "Mens Mid Light Wash Denim Pant - Regular Fit",
    category: "Mens Jeans Pant",
    brand: "Loomora",
    price: 1290,
    color: "#475569",
    colorName: "Slate Grey",
    src: "/images/men/w-3.jpg",
    badge: "New",
    sizes: ["30", "32", "34", "36"],
    fabric: "Denim",
    fit: "Regular Fit",
    length: "Full Length",
    productType: "Denim",
  },
  {
    id: "m-5",
    name: "Mens Mid Light Wash Denim Pant - Regular Fit",
    category: "Mens Jeans Pant",
    brand: "DHEU",
    price: 1390,
    color: "#0284c7",
    colorName: "Sky Blue",
    src: "/images/men/w-4.jpg",
    badge: "New",
    sizes: ["30", "32", "34", "36"],
    fabric: "Denim",
    fit: "Regular Fit",
    length: "Full Length",
    productType: "Denim",
  },
  {
    id: "m-6",
    name: "Mens Premium Rust Bomber Jacket - Regular Fit",
    category: "Mens Jacket",
    brand: "Loomora",
    price: 2000,
    oldPrice: 2500,
    color: "#b45309",
    colorName: "Rust Brown",
    src: "/images/c-1.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Bamboo Fiber & Synthetic",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    length: "Full Length",
    productType: "Jacket",
  },
  {
    id: "m-7",
    name: "Mens Crimson Velvet Formal Blazer",
    category: "Mens Jacket",
    brand: "Loomora Signature",
    price: 4500,
    oldPrice: 5200,
    color: "#dc2626",
    colorName: "Crimson Red",
    src: "/images/c-6.avif",
    badge: "New",
    sizes: ["38", "40", "42"],
    fabric: "Velvet",
    fit: "Slim Fit",
    sleeve: "Full Sleeve",
    neck: "Collar",
    length: "Full Length",
    productType: "Blazer",
    festive: ["Eid 2026", "Puja 2026"],
  },
  {
    id: "m-8",
    name: "Mens Crisp Pure Egyptian Cotton White Shirt",
    category: "Mens Formal Shirt",
    brand: "Loomora",
    price: 1750,
    oldPrice: 2100,
    color: "#ffffff",
    colorName: "White",
    src: "/images/c-9.avif",
    badge: "New",
    sizes: ["38", "40", "42", "44"],
    fabric: "Cotton jacquard Shirting Fabric",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Collar",
    length: "Full Length",
    productType: "Shirt",
    festive: ["Eid 2026"],
  },
  {
    id: "m-9",
    name: "Mens Classic Denim Trucker Jacket",
    category: "Mens Jacket",
    brand: "DHEU",
    price: 2199,
    color: "#1e3a8a",
    colorName: "Classic Denim",
    src: "/images/c-3.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Denim",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Collar",
    length: "Full Length",
    productType: "Denim",
  },
  {
    id: "m-10",
    name: "Mens Heather Grey Cotton Crewneck Tee",
    category: "Mens T-Shirt",
    brand: "Loomora",
    price: 890,
    oldPrice: 1100,
    color: "#71717a",
    colorName: "Grey",
    src: "/images/c-7.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Cotton",
    fit: "Regular Fit",
    sleeve: "Half Sleeve",
    neck: "Round",
    length: "Short",
    productType: "T-Shirt",
  },
  {
    id: "m-11",
    name: "Mens Navy Fleece Hoodie & Denim Set",
    category: "Mens Hoodie",
    brand: "Loomora",
    price: 1224,
    oldPrice: 1360,
    color: "#12509b",
    colorName: "Navy",
    src: "/images/c-8.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Fleece",
    fit: "Over-sized",
    sleeve: "Full Sleeve",
    neck: "Hooded Neck",
    length: "Long",
    productType: "Hoodie",
    addition: ["Print"],
    set: "2pcs",
  },
  {
    id: "m-12",
    name: "Mens Everyday Fleece Relaxed Sweatshirt",
    category: "Mens Sweatshirt",
    brand: "Loomora",
    price: 1650,
    oldPrice: 1990,
    color: "#f5f5f4",
    colorName: "Off White",
    src: "/images/c-2.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Fleece Fabric",
    fit: "Boxy Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Long",
    productType: "Sweatshirt",
  },
  {
    id: "w-1",
    name: "Womens Floral Embroidered Kurti Set - Regular Fit",
    category: "Womens Kurti",
    brand: "Loomora",
    price: 2490,
    oldPrice: 3200,
    color: "#fda4af",
    colorName: "Pastel Rose",
    src: "/images/women/women.avif",
    badge: "New",
    sizes: ["38", "40", "42"],
    fabric: "Cotton",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Full Length",
    addition: ["Embroidery"],
    festive: ["Puja 2026"],
    productType: "Kurti",
    set: "2pcs",
  },
  {
    id: "w-2",
    name: "Womens Crimson Silk Traditional Handwoven Saree",
    category: "Womens Saree",
    brand: "Loomora",
    price: 1550,
    color: "#dc2626",
    colorName: "Crimson Red",
    src: "/images/women/m-1.jpg",
    badge: "New",
    sizes: ["FREE SIZE"],
    fabric: "Silk",
    festive: ["Puja 2026"],
    productType: "Saree",
  },
  {
    id: "w-3",
    name: "Womens Rose Festive Printed Saree with Zari Border",
    category: "Womens Saree",
    brand: "DHEU",
    price: 1550,
    color: "#ec4899",
    colorName: "Rose Pink",
    src: "/images/women/m-2.jpg",
    badge: "New",
    sizes: ["FREE SIZE"],
    fabric: "Silk",
    addition: ["Print"],
    festive: ["Puja 2026"],
    productType: "Saree",
  },
  {
    id: "w-4",
    name: "Womens Pearl White Classic Festive Saree",
    category: "Womens Saree",
    brand: "Loomora",
    price: 1550,
    color: "#e5e7eb",
    colorName: "Pearl White",
    src: "/images/women/m-3.jpg",
    badge: "New",
    sizes: ["FREE SIZE"],
    fabric: "Silk",
    festive: ["Eid 2026", "Puja 2026"],
    productType: "Saree",
  },
  {
    id: "w-5",
    name: "Womens 2 Pcs Pastel Ensemble Set - Regular Fit",
    category: "Womens 2 Pcs Set",
    brand: "Loomora Women",
    price: 2890,
    oldPrice: 3500,
    color: "#f9a8d4",
    colorName: "Pastel Pink",
    src: "/images/women/m-4.jpg",
    badge: "New",
    sizes: ["38", "40", "42"],
    fabric: "Cotton & Spandex",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Full Length",
    festive: ["Puja 2026"],
    productType: "Kurti",
    set: "2pcs",
  },
  {
    id: "w-6",
    name: "Womens Ethnic Festive Kurti & Trouser 2 Pcs Set",
    category: "Womens 2 Pcs Set",
    brand: "Loomora",
    price: 2690,
    color: "#dc2626",
    colorName: "Scarlet Red",
    src: "/images/women/m-5.jpg",
    badge: "New",
    sizes: ["38", "40", "42"],
    fabric: "Cotton",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Band Collar",
    length: "Full Length",
    addition: ["Karchupi"],
    festive: ["Eid 2026", "Puja 2026"],
    productType: "Kurti",
    set: "2pcs",
  },
  {
    id: "w-7",
    name: "Womens Soft Cashmere Knit Cardigan - Rose",
    category: "Womens Cardigan",
    brand: "Loomora Signature",
    price: 23590,
    oldPrice: 27400,
    color: "#fda4af",
    colorName: "Blush Rose",
    src: "/images/c-10.avif",
    badge: "New",
    sizes: ["FREE SIZE"],
    fabric: "Cashmere",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Rib Collar",
    length: "Long",
    productType: "Cardigan",
  },
  {
    id: "w-8",
    name: "Womens Everyday Fleece Minimalist Sweatshirt",
    category: "Womens Tops",
    brand: "Loomora",
    price: 6000,
    oldPrice: 6900,
    color: "#f5f5f4",
    colorName: "Chalk White",
    src: "/images/c-2.avif",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    fabric: "Fleece Fabric",
    fit: "Over-sized",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Long",
    productType: "Sweatshirt",
  },
  {
    id: "w-9",
    name: "Womens Bohemian Botanical Print Casual Tunic Dress",
    category: "Womens Tops",
    brand: "DHEU",
    price: 2890,
    color: "#059669",
    colorName: "Forest Green",
    src: "/images/c-4.avif",
    badge: "New",
    sizes: ["S", "M", "L"],
    fabric: "Cotton & Modal Print",
    fit: "Regular Fit",
    sleeve: "Half Sleeve",
    neck: "Round",
    length: "Full Length",
    addition: ["Print"],
    festive: ["Boishak 2026"],
    productType: "Dress",
  },
  {
    id: "w-10",
    name: "Womens Warm Cozy Winter Fleece Jacket",
    category: "Womens Winter Wear",
    brand: "Loomora",
    price: 2190,
    oldPrice: 2650,
    color: "#e11d48",
    colorName: "Wine Berry",
    src: "/images/c-5.avif",
    badge: "New",
    sizes: ["M", "L", "XL"],
    fabric: "Fleece",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Hooded Neck",
    length: "Full Length",
    productType: "Jacket",
  },
  {
    id: "k-1",
    name: "Boys Cotton Pique Polo Shirt - Regular Fit",
    category: "Boys Polo",
    brand: "Loomora Kids",
    price: 690,
    oldPrice: 850,
    color: "#0f766e",
    colorName: "Sea Green",
    src: "/images/men/w-1.jpg",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    fabric: "Cotton & Spandex",
    fit: "Regular Fit",
    sleeve: "Half Sleeve",
    neck: "Rib Collar",
    length: "Short",
    productType: "Polo",
  },
  {
    id: "k-2",
    name: "Boys Graphic Print Short Sleeve T-Shirt",
    category: "Boys T-Shirt",
    brand: "Loomora Kids",
    price: 490,
    color: "#71717a",
    colorName: "Heather Grey",
    src: "/images/c-7.avif",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    fabric: "Cotton",
    fit: "Regular Fit",
    sleeve: "Half Sleeve",
    neck: "Round",
    length: "Short",
    productType: "T-Shirt",
    addition: ["Print"],
  },
  {
    id: "k-3",
    name: "Girls Floral Festive Printed Frock",
    category: "Girls Frock",
    brand: "DHEU Junior",
    price: 1190,
    oldPrice: 1450,
    color: "#fda4af",
    colorName: "Blush Pink",
    src: "/images/women/women.avif",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    fabric: "Cotton",
    fit: "Regular Fit",
    sleeve: "Half Sleeve",
    neck: "Round",
    length: "Full Length",
    addition: ["Print"],
    festive: ["Puja 2026"],
    productType: "Dress",
  },
  {
    id: "k-4",
    name: "Girls 2 Pcs Pastel Traditional Kurti & Trouser Set",
    category: "Girls Kurti Set",
    brand: "Loomora Kids",
    price: 1390,
    color: "#f9a8d4",
    colorName: "Rose Pink",
    src: "/images/women/m-4.jpg",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    fabric: "Cotton & Spandex",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Full Length",
    festive: ["Puja 2026"],
    productType: "Kurti",
    set: "2pcs",
  },
  {
    id: "k-5",
    name: "Boys Stretch Comfort Denim Pant",
    category: "Boys Jeans Pant",
    brand: "Loomora Kids",
    price: 990,
    oldPrice: 1250,
    color: "#1e3a8a",
    colorName: "Navy Blue",
    src: "/images/men/w-2.jpg",
    badge: "New",
    sizes: ["6-7Y", "8-9Y", "10-11Y"],
    fabric: "Denim",
    fit: "Slim Fit",
    length: "Full Length",
    productType: "Denim",
  },
  {
    id: "k-6",
    name: "Kids Warm Fleece Hoodie & Jogger Set",
    category: "Kids Winter Wear",
    brand: "Loomora Kids",
    price: 950,
    oldPrice: 1150,
    color: "#12509b",
    colorName: "Royal Navy",
    src: "/images/c-8.avif",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    fabric: "Fleece",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Hooded Neck",
    length: "Long",
    productType: "Hoodie",
    set: "2pcs",
  },
  {
    id: "k-7",
    name: "Girls Handcrafted Festive Silk Frock",
    category: "Girls Frock",
    brand: "DHEU Junior",
    price: 1450,
    color: "#ec4899",
    colorName: "Rose Quartz",
    src: "/images/women/m-2.jpg",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    fabric: "Silk",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Full Length",
    festive: ["Puja 2026"],
    productType: "Dress",
  },
  {
    id: "k-8",
    name: "Kids Cozy Knitted Cardigan Sweater",
    category: "Kids Winter Wear",
    brand: "Loomora Kids",
    price: 1290,
    color: "#fda4af",
    colorName: "Pastel Rose",
    src: "/images/c-10.avif",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    fabric: "Cashmere",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Rib Collar",
    length: "Long",
    productType: "Cardigan",
  },
  {
    id: "k-9",
    name: "Boys Classic Denim Trucker Jacket",
    category: "Kids Jacket",
    brand: "DHEU Junior",
    price: 1590,
    oldPrice: 1890,
    color: "#1e3a8a",
    colorName: "Indigo Blue",
    src: "/images/c-3.avif",
    badge: "New",
    sizes: ["6-7Y", "8-9Y", "10-11Y"],
    fabric: "Denim",
    fit: "Regular Fit",
    sleeve: "Full Sleeve",
    neck: "Collar",
    length: "Full Length",
    productType: "Jacket",
  },
  {
    id: "k-10",
    name: "Kids Everyday Relaxed Fleece Sweatshirt",
    category: "Kids Sweatshirt",
    brand: "Loomora Kids",
    price: 890,
    color: "#f5f5f4",
    colorName: "Chalk White",
    src: "/images/c-2.avif",
    badge: "New",
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    fabric: "Fleece Fabric",
    fit: "Boxy Fit",
    sleeve: "Full Sleeve",
    neck: "Round",
    length: "Long",
    productType: "Sweatshirt",
  },
];

export function getProduct(id: string): CatalogProduct | undefined {
  return catalog.find((product) => product.id === id);
}
